INSERT INTO category (id, name) VALUES
    (1, 'Fruits'),
    (2, 'Vegetables'),
    (3, 'Grains & Bakery'),
    (4, 'Dairy & Eggs'),
    (5, 'Meat & Fish'),
    (6, 'Nuts & Seeds'),
    (7, 'Beverages'),
    (8, 'Other');

INSERT INTO product (name, price_cents, image_url, category_id, unit) VALUES
    ('Almonds', 499, '/images/almonds.jpg', 6, 'per 200g'),
    ('Apple', 149, '/images/apple.jpg', 1, 'per piece'),
    ('Avocado', 229, '/images/avocado.jpg', 1, 'per piece'),
    ('Banana', 119, '/images/banana.jpg', 1, 'per piece'),
    ('Barley', 219, '/images/barley.jpg', 3, 'per kg'),
    ('Beetroot', 149, '/images/beetroot.jpg', 2, 'per 500g'),
    ('Bell Pepper', 199, '/images/bellpepper.jpg', 2, 'per piece'),
    ('Blueberries', 329, '/images/blueberries.jpg', 1, 'per 125g'),
    ('Bread', 199, '/images/bread.jpg', 3, 'per loaf'),
    ('Broccoli', 179, '/images/broccoli.jpg', 2, 'per piece'),
    ('Brown Rice', 349, '/images/brownrice.jpg', 3, 'per kg'),
    ('Buckwheat', 299, '/images/buckwheat.jpg', 3, 'per kg'),
    ('Butter', 229, '/images/butter.jpg', 4, 'per 250g'),
    ('Carrot', 89, '/images/carrot.jpg', 2, 'per 500g'),
    ('Cashews', 549, '/images/cashews.jpg', 6, 'per 200g'),
    ('Cauliflower', 189, '/images/cauliflower.jpg', 2, 'per piece'),
    ('Cheese', 359, '/images/cheese.jpg', 4, 'per 200g'),
    ('Chicken Breast', 699, '/images/chickenbreast.jpg', 5, 'per 500g'),
    ('Chia Seeds', 379, '/images/chia.jpg', 6, 'per 200g'),
    ('Cod', 749, '/images/cod.jpg', 5, 'per 400g'),
    ('Coffee Beans', 699, '/images/coffeebeans.jpg', 7, 'per 250g'),
    ('Cottage Cheese', 249, '/images/cottagecheese.jpg', 4, 'per 200g'),
    ('Cucumber', 99, '/images/cucumber.jpg', 2, 'per piece'),
    ('Dark Chocolate', 429, '/images/darkchocolate.jpg', 8, 'per 100g'),
    ('Eggplant', 199, '/images/eggplant.jpg', 2, 'per piece'),
    ('Eggs', 259, '/images/egg.jpg', 4, 'per dozen'),
    ('Flax Seeds', 359, '/images/flaxseeds.jpg', 6, 'per 200g'),
    ('Garlic', 129, '/images/garlic.jpg', 2, 'per 100g'),
    ('Goat Cheese', 379, '/images/goatcheese.jpg', 4, 'per 150g'),
    ('Granola', 329, '/images/granola.jpg', 3, 'per box'),
    ('Grapes', 279, '/images/grapes.jpg', 1, 'per 500g'),
    ('Greek Yogurt', 299, '/images/greekyogurt.jpg', 4, 'per cup'),
    ('Green Tea', 249, '/images/greentea.jpg', 7, 'per box'),
    ('Hazelnuts', 519, '/images/hazelnuts.jpg', 6, 'per 200g'),
    ('Honey', 499, '/images/honey.jpg', 8, 'per jar'),
    ('Kale', 169, '/images/kale.jpg', 2, 'per bunch'),
    ('Kiwi', 159, '/images/kiwi.jpg', 1, 'per piece'),
    ('Kombucha', 379, '/images/kombucha.jpg', 7, 'per bottle'),
    ('Lamb', 1099, '/images/lamb.jpg', 5, 'per 500g'),
    ('Lettuce', 139, '/images/lettuce.jpg', 2, 'per head'),
    ('Mackerel', 699, '/images/mackerel.jpg', 5, 'per 300g'),
    ('Mango', 259, '/images/mango.jpg', 1, 'per piece'),
    ('Maple Syrup', 649, '/images/maplesyrup.jpg', 8, 'per bottle'),
    ('Meat', 699, '/images/meat.jpg', 5, 'per 500g'),
    ('Milk', 189, '/images/milk.jpg', 4, 'per liter'),
    ('Mineral Water', 129, '/images/mineralwater.jpg', 7, 'per 500ml'),
    ('Oats', 229, '/images/oats.jpg', 3, 'per 500g'),
    ('Olive Oil', 599, '/images/oliveoil.jpg', 8, 'per liter'),
    ('Onion', 99, '/images/onion.jpg', 2, 'per kg'),
    ('Orange', 189, '/images/orange.jpg', 1, 'per piece'),
    ('Orange Juice', 299, '/images/orangejuice.jpg', 7, 'per liter'),
    ('Papaya', 329, '/images/papaya.jpg', 1, 'per piece'),
    ('Peach', 199, '/images/peach.jpg', 1, 'per piece'),
    ('Peanut Butter', 439, '/images/peanutbutter.jpg', 8, 'per jar'),
    ('Pear', 169, '/images/pear.jpg', 1, 'per piece'),
    ('Pineapple', 299, '/images/pineapple.jpg', 1, 'per piece'),
    ('Pistachios', 599, '/images/pistachios.jpg', 6, 'per 200g'),
    ('Pita Bread', 219, '/images/pita.jpg', 3, 'per pack'),
    ('Pumpkin Seeds', 389, '/images/pumpkinseeds.jpg', 6, 'per 200g'),
    ('Quinoa', 399, '/images/quinoa.jpg', 3, 'per 500g'),
    ('Salmon', 899, '/images/salmon.jpg', 5, 'per 300g'),
    ('Sardines', 459, '/images/sardines.jpg', 5, 'per can'),
    ('Shrimp', 879, '/images/shrimp.jpg', 5, 'per 250g'),
    ('Sourdough Bread', 249, '/images/sourdough.jpg', 3, 'per loaf'),
    ('Spinach', 159, '/images/spinach.jpg', 2, 'per bunch'),
    ('Strawberries', 349, '/images/strawberries.jpg', 1, 'per 250g'),
    ('Strawberry Jam', 369, '/images/strawberryjam.jpg', 8, 'per jar'),
    ('Sweet Potato', 179, '/images/sweetpotato.jpg', 2, 'per 500g'),
    ('Tomato', 109, '/images/tomato.jpg', 2, 'per 500g'),
    ('Turkey', 799, '/images/turkey.jpg', 5, 'per 500g'),
    ('Tuna', 859, '/images/tuna.jpg', 5, 'per 300g'),
    ('Walnuts', 529, '/images/walnuts.jpg', 6, 'per 200g'),
    ('Watermelon', 499, '/images/watermelon.jpg', 1, 'per piece'),
    ('Whole Wheat Pasta', 249, '/images/wholewheatpasta.jpg', 3, 'per 500g'),
    ('Zucchini', 149, '/images/zucchini.jpg', 2, 'per piece');